image: quickcorp/qcobjects:latest

pages:
  stage: deploy
  script:
  - npm i qcobjects && npm i -D eslint-config-qcobjects
  - npm ci
  - npm test
  - mkdir public
  - npm run publish:web
  - cp _redirects public/
  - cp -r node_modules public/
  artifacts:
    paths:
    - node_modules/qcobjects-sdk
    - build
    - public
  only:
  - main
