image: quickcorp/qcobjects:latest

pages:
  stage: deploy
  before_script:
  - apk add openssh git curl rsync
  script:
  - npm i qcobjects && npm i -D eslint-config-qcobjects
  - npm ci
  - npm test
  - mkdir public
  - npm run publish:web
  - cp _redirects public/
  artifacts:
    paths:
    - build
    - public
  only:
  - main
