image: quickcorp/qcobjects:latest

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -Rf * public/ | grep -v [public]
  - cd public
  - npm i
  - npm test
  artifacts:
    paths:
    - public
  only:
  - master
